import { TaskItem, CalendarEvent, MenuItem } from './types';

export const initialTasks: TaskItem[] = [
  {
    id: 'task-1',
    title: '关于报请审批《广州银行2020年第三季度信息科技建设项目立项申请》的签报',
    category: '公文管理',
    type: '签报',
    urgent: true,
    sender: '郑成功',
    department: '金融科技部',
    time: '2020-07-29 15:00',
    section: '待办',
    unread: true,
    serialNumber: 'GZ-QB-2020-0041',
    description: '审阅信息技术部第二团队2020年第三季度软件开发进度成果及生产环境部署规划。请各项目负责人提前准备汇报PPT材料。'
  },
  {
    id: 'task-2',
    title: '关于申请采购新一代分布式核心银行系统SIT测试环境软硬件资源的签报',
    category: '公文管理',
    type: '签报',
    urgent: false,
    sender: '李白',
    department: '零售金融管理部',
    time: '2020-07-28 14:10',
    section: '待办',
    unread: true,
    serialNumber: 'GZ-QB-SIT-001',
    description: '关于广州银行新一代数字化协同办公系统（OA）SIT测试合同审批及服务交付商准入资格审查报告。'
  },
  {
    id: 'task-3',
    title: '广东省地方金融监督管理局关于加强银行业金融机构信息科技风险防控工作的指导意见（收文）',
    category: '公文管理',
    type: '收文',
    urgent: false,
    sender: '李白',
    department: '零售金融管理部',
    time: '2020-07-28 10:20',
    section: '待办',
    unread: true,
    serialNumber: 'GZ-SW-SIT-002',
    description: '广东省政务服务数据管理局关于推广数字化办公系统对接标准技术指南的通知收文登记审批。'
  },
  {
    id: 'task-4',
    title: '关于金融科技部郑成功同志申请2020年度暑期带薪年休假的审批流程',
    category: '流程管理',
    type: '休假',
    urgent: false,
    sender: '郑成功',
    department: '金融科技部',
    time: '2020-07-28 09:30',
    section: '待办',
    unread: true,
    serialNumber: 'GZ-XJ-VAC-003',
    description: '总行软件开发中心郑成功关于2020年暑期带薪年休假申请流程。共计5个工作日。'
  },
  {
    id: 'task-5',
    title: '关于转发《中国人民银行办公厅关于进一步加强支付结算管理防范电信网络新型违法犯罪有关事项的通知》的收文',
    category: '流程管理',
    type: '收文',
    urgent: false,
    sender: '李白',
    department: '零售金融管理部',
    time: '2020-07-28 10:27',
    section: '待办',
    unread: true,
    serialNumber: 'GZ-SW-SIT-004',
    description: '软件外包开发服务框架协议（sit环境第三方对接模块）的技术说明材料及收签发。'
  },
  {
    id: 'task-6',
    title: '关于印发《广州银行股份有限公司2020年度软件著作权与专利技术申报工作方案》的通知',
    category: '公文管理',
    type: '发文',
    urgent: true,
    sender: '杜甫',
    department: '公司金融部',
    time: '2020-07-27 16:30',
    section: '待办',
    unread: false,
    serialNumber: 'GZ-FW-2020-0112',
    description: '关于广州银行分布式账本关键技术专利与软件著作权申请流程。'
  },
  {
    id: 'task-7',
    title: '关于天河数据中心B区高密机柜供电及智能冷却系统升级改造追加预算的申报签报',
    category: '公文管理',
    type: '签报',
    urgent: false,
    sender: '白居易',
    department: '金融科技部',
    time: '2020-07-27 11:00',
    section: '待办',
    unread: false,
    serialNumber: 'GZ-QB-2020-0039',
    description: '关于天河数据中心B区高密机柜供电与智能冷却系统升级改造追加预算的申报意见。'
  },
  {
    id: 'task-8',
    title: '关于天河智慧支行新设网点备案材料使用总行公章用印的申请',
    category: '公文管理',
    type: '印章',
    urgent: false,
    sender: '王建国',
    department: '总行办公室',
    time: '2020-07-26 14:20',
    section: '待办',
    unread: true,
    serialNumber: 'GZ-YZ-2020-0056',
    description: '天河支行申请使用总行公章对新设智慧网点备案材料进行用印，需办公室审批。'
  },
  {
    id: 'task-9',
    title: '金融科技部员工李明同志申请婚假休假（15个自然日）的审批',
    category: '流程管理',
    type: '休假',
    urgent: false,
    sender: '李明',
    department: '金融科技部',
    time: '2020-07-26 09:15',
    section: '待办',
    unread: true,
    serialNumber: 'GZ-XJ-2020-0088',
    description: '金融科技部员工李明申请婚假休假，共计15个自然日，需部门负责人审批。'
  },
  // To-Read Section Items (待阅)
  {
    id: 'read-1',
    title: '【重要通知】关于全行部署2020年第三季度网络安全红蓝对抗实战演练的紧急通知',
    category: '信息公告',
    type: '收文',
    urgent: true,
    sender: '系统管理员',
    department: '信息科技部',
    time: '2020-07-29 09:00',
    section: '待阅',
    unread: true,
    serialNumber: 'GZ-SW-2020-089',
    description: '根据监管部门关于提升金融信息系统网络对抗防御水平的要求，我行将于本周五晚开展蓝军渗透对抗实战模拟。请各系统运维保障人员到岗值班。'
  },
  {
    id: 'read-2',
    title: '关于表彰2020年第二季度全行核心业务系统敏捷迭代开发突出贡献团队及个人的决定',
    category: '信息公告',
    type: '发文',
    urgent: false,
    sender: '人力资源部',
    department: '人力资源部',
    time: '2020-07-28 17:00',
    section: '待阅',
    unread: true,
    serialNumber: 'GZ-FW-2020-045',
    description: '表彰在二季度全行核心业务群组敏捷迭代开发、零风险上线中做出突出贡献的一线软件工程师名单。'
  },
  {
    id: 'read-3',
    title: '关于规范各分行级自研及采购科技项目立项审批额度与合规红线管理的签报指导意见',
    category: '规章制度',
    type: '签报',
    urgent: false,
    sender: '规章管理处',
    department: '合规管理部',
    time: '2020-07-28 10:15',
    section: '待阅',
    unread: true,
    serialNumber: 'GZ-QB-2020-012',
    description: '针对各分行级自研或采购的中小科技项目，进一步规范审批额度流程及风险合规红线规范。'
  },
  {
    id: 'read-4',
    title: '关于印发《广州银行股份有限公司知识产权资产管理办法（暂行）》的通知',
    category: '规章制度',
    type: '发文',
    urgent: false,
    sender: '总行办公室',
    department: '总行办公室',
    time: '2020-07-26 14:00',
    section: '待阅',
    unread: false,
    serialNumber: 'GZ-FW-2020-0098',
    description: '明确各科技中心、创新实验室所沉淀的软件代码、发明专利、原型设计的归属、估值及授权标准。'
  },
  {
    id: 'read-5',
    title: '关于2020年上半年度科技中心大楼食堂窗口服务满意度调查结果及后续整改举措的通报',
    category: '流程管理',
    type: '收文',
    urgent: false,
    sender: '行政后勤部',
    department: '行政后勤部',
    time: '2020-07-25 15:30',
    section: '待阅',
    unread: false,
    serialNumber: 'GZ-SW-2020-154',
    description: '2020年上半年度科技开发中心大楼食堂窗口及服务保障满意度调查反馈结果与后续改良举措说明。'
  },
  {
    id: 'read-6',
    title: '关于征求《广州银行印章使用管理办法（2020修订版）》修改意见的通知',
    category: '规章制度',
    type: '印章',
    urgent: false,
    sender: '总行办公室',
    department: '总行办公室',
    time: '2020-07-25 10:00',
    section: '待阅',
    unread: true,
    serialNumber: 'GZ-YZ-2020-0032',
    description: '关于修订全行印章使用管理办法的征求意见稿，涉及公章、合同章、财务章的使用权限变更。'
  },
  {
    id: 'read-7',
    title: '关于统一规范全行员工各类休假（年假、病假、婚假、产假）审批权限及流程的补充规定',
    category: '规章制度',
    type: '休假',
    urgent: false,
    sender: '人力资源部',
    department: '人力资源部',
    time: '2020-07-24 16:45',
    section: '待阅',
    unread: true,
    serialNumber: 'GZ-XJ-2020-0019',
    description: '针对全行员工各类休假（年假、病假、婚假、产假）的审批权限和流程进行统一规范的补充说明。'
  },
  {
    id: 'read-8',
    title: '关于呈报《广州银行股份有限公司2020年上半年整体经营情况分析报告》的签报',
    category: '信息公告',
    type: '签报',
    urgent: false,
    sender: '战略规划部',
    department: '战略规划部',
    time: '2020-07-24 09:00',
    section: '待阅',
    unread: false,
    serialNumber: 'GZ-QB-2020-0100',
    description: '2020年上半年全行经营数据汇总分析，包含存贷款规模、利润指标、不良率等核心经营数据。'
  },
];

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal-1',
    timeRange: '10:00-11:00',
    title: '会议安排 会议一',
    type: '会议安排',
    description: '讨论新OA办公协作系统的视觉还原与界面动效还原，确定第一期上线核心清单。'
  },
  {
    id: 'cal-2',
    timeRange: '12:00-13:00',
    title: '我的日历 需求说明书',
    type: '我的日历',
    description: '审核交付关于《广州银行数据可视化决策白皮书设计说明》的草稿规范与接口契约。'
  },
  {
    id: 'cal-3',
    timeRange: '14:00-15:30',
    title: '信息技术部周例会',
    type: '会议安排',
    description: '每周技术团队站会，同步各项目进度、技术难点及资源调配。'
  },
];

export const menuItems: MenuItem[] = [
  { id: 'flow', label: '流程管理', iconName: 'Workflow', badge: 36 },
  { id: 'archive', label: '公文管理', iconName: 'FileText' },
  { id: 'announcement', label: '信息公告', iconName: 'Volume2' },
  { id: 'rule', label: '规章制度', iconName: 'ShieldAlert' },
  { id: 'meeting1', label: '会议管理', iconName: 'Video' },
  { id: 'calendar1', label: '日程管理', iconName: 'Calendar' },
  { id: 'attend1', label: '考勤管理', iconName: 'UserCheck' },
  { id: 'news', label: '新闻管理', iconName: 'Globe' },
  { id: 'knowledge', label: '知识仓库', iconName: 'BookOpen' },
  { id: 'oversight', label: '督办管理', iconName: 'ClipboardCheck' }
];

export const quickActions = [
  { id: 'directory', label: '通讯录', iconName: 'Users', color: 'bg-indigo-600' },
  { id: 'email', label: '邮箱', iconName: 'Mail', color: 'bg-sky-600', badge: 5 },
  { id: 'new-process', label: '新建流程', iconName: 'PlusCircle', color: 'bg-emerald-600' },
  { id: 'draft-dispatch', label: '发文拟稿', iconName: 'FileEdit', color: 'bg-teal-600' },
  { id: 'receive-reg', label: '收文登记', iconName: 'FileSymlink', color: 'bg-amber-600' },
  { id: 'draft-report', label: '签报拟稿', iconName: 'Bookmark', color: 'bg-cyan-600' },
  { id: 'more', label: '更多', iconName: 'Grid', color: 'bg-slate-600' }
];
